apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-boot-app
  labels:
    app: hello-spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-boot-app
  template:
    metadata:
      labels:
        app: hello-spring-boot-app
        cryostat.io/target: "true"  # <-- Required for Cryostat discovery
      annotations:
        promtail.io/scrape: "true"
        promtail.io/labels: '{"app":"springboot"}'
    spec:
      containers:
        - name: hello-spring-boot-app
          image: nazia141/hello-spring-boot-app:1.1
          ports:
            - name: http
              containerPort: 8080
            - name: jmx
              containerPort: 9999
            - name: rmi
              containerPort: 10000
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:+FlightRecorder
                -XX:StartFlightRecording=duration=5m,filename=/tmp/recording.jfr,settings=profile
                -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.port=9999
                -Dcom.sun.management.jmxremote.rmi.port=10000
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.authenticate=false
                -Djava.rmi.server.hostname=$(POD_IP)
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: hello-spring-boot-app
spec:
  type: NodePort
  selector:
    app: hello-spring-boot-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: jmx
      port: 9999
      targetPort: 9999
      nodePort: 30999
    - name: rmi
      port: 10000
      targetPort: 10000
      nodePort: 31000
