apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cryostat-read
  namespace: spring-boot-app
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cryostat-access
  namespace: spring-boot-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cryostat-read
subjects:
- kind: ServiceAccount
  name: cryostat
  namespace: cryostat
