# Role in the target namespace (spring-boot-app)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spring-boot-app
  name: cryostat-read
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding in the target namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: spring-boot-app
  name: cryostat-read-binding
subjects:
  - kind: ServiceAccount
    name: cryostat
    namespace: cryostat
roleRef:
  kind: Role
  name: cryostat-read
  apiGroup: rbac.authorization.k8s.io
